<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{3330ec8e-e841-47c7-9b9d-772dabe85526}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbCount		: FB_Count;
	bCount		: BOOL;
	nCounter	: INT;
	nCounter2	: INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbCount(
	bCount			:= bCount,
	nCountIncrement	:= 2,
	nCounterValue	=> nCounter
);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>