<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MyLibFunction" Id="{4003c87c-9b6a-4d73-9005-69068e600125}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MyLibFunction
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>